# Generated by Django 4.0.4 on 2024-06-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalorieEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('food_item', models.CharField(max_length=100)),
                ('calories', models.PositiveIntegerField()),
            ],
        ),
    ]
